catalog:
  '@gabortorma/antfu-eslint-config': ^3.2.0
  '@gabortorma/mwm': ^0.9.3
  '@nuxt/eslint': 1.7.0
  '@types/node': ^24.1.0
  '@typescript-eslint/utils': ^8.38.0
  '@vue/compiler-sfc': ^3.5.18
  dotenv-cli: ^9.0.0
  nuxi: ^3.26.4
  nuxt: ^4.0.1
  release-it: ^19.0.4
  release-it-pnpm: ^4.6.6
  typescript: 5.8.3
  vite-plugin-eslint2: 5.0.4
  vue: ^3.5.18
  vue-tsc: 3.0.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
